apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dev
  namespace: <namespace>
rules:
  - verbs:
      - '*'
    apiGroups:
      - ''
    resources:
      - '*'
  - verbs:
      - '*'
    apiGroups:
      - extensions
    resources:
      - '*'
